version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hi-c-map-for-assembly-manual-curation.ga
  testParameterFiles:
  - /hi-c-map-for-assembly-manual-curation-tests.yml
  authors:
  - name: Patrik Smeds
    orcid: 0000-0001-6228-2785
  - name: Delphine Lariviere
    orcid: 0000-0001-6421-3484
